### ISSUE TITLE
Dump latest 2.21 static data

### ISSUE THREAD

**Issue by Rodze** [Da-Teach/RaidStaticData#1]
Sometimes the app is updated, but the static data is updated a few days later when they enable the new features or when they make any simple data fix that doesn't require recompiling.

The one available in this repo (v0.223) is not the latest one. The current game version is from oct 5th. (the revision date at the end of the json).

Is it too complicated for someone who has never built a project like this to learn how to dump this data? (so I wouldn't have to annoy you asking about it every time lol).

Thanks!

**Comment by Da-Teach** [comment]
I get this data by injecting code into Raid, not for the faint of heart. I'll see if I can got some monitoring on it so I can update it more frequently.

**Comment by Da-Teach** [comment]
Ok I've added some monitoring for this in my own raid, uhm, "clicker", so the static data will get updated as soon as Raid updates it.  I've also begun thinking about exposing most of the static data on the website, but didn't get around to that yet.

**Comment by zerfl** [comment]
If you don't mind me asking... 
I am injecting my own code and retrieving pretty much the same data you have but all my keys are mangled/abbreviated:

Yours:
```
      {
        "Id": 21120,
        "Name": {
          "Key": "l10n:hero-type/name?id=21120#static",
          "DefaultValue": "Mortu-Macaab"
        },
        "AvatarName": "21120",
        "ModelName": "2012_SmelterDemon",
        "Element": 3,
        "Role": 0,
        "Fraction": 0,
        "Rarity": 5,
        "BaseStats": {
          "Health": 1073741824000,
          "Attack": 468151435264,
          "Defence": 352187318272,
          "Speed": 515396075520,
          "Resistance": 128849018880,
          "Accuracy": 0,
          "CriticalChance": 64424509440,
          "CriticalDamage": 214748364800,
          "CriticalHeal": 214748364800
        },
        "SkillTypeIds": [
          9901,
          9902,
          9903,
          9904,
          200000
        ],
        "BossData": {
          "IsUnkillable": 0
        },
        "SummonWeight": 0,
        "IsLocationOnly": 1,
        "Status": 40,
        "Brain": 0
      },
```

Mine:
```
{
	"i":21120,
	"hn":{
		"k":"l10n:hero-type/name?id=21120#static",
		"d":"Mortu-Macaab"
	},
	"au":"21120",
	"mu":"2012_SmelterDemon",
	"e":3,
	"r":0,
	"f":0,
	"g":5,
	"b":{
		"h":1073741824000,
		"a":468151435264,
		"d":352187318272,
		"s":515396075520,
		"r":128849018880,
		"t":0,
		"u":64424509440,
		"m":214748364800,
		"c":214748364800
	},
	"s":[
		9901,
		9902,
		9903,
		9904,
		200000
	],
	"bd":{
		"u":0
	},
	"sw":0,
	"lo":1,
	"rs":40,
	"br":0
}
```
I am calling the built-in method to extract the data. Are you rewriting these before outputting or are you getting the proper data returned already?

**Comment by Da-Teach** [comment]
Try using JsonMain.ToJsonStr function (not sure which one you are using) and pass "true" for the second parameter.

**Comment by zerfl** [comment]
This worked perfectly, thank you for the hint.

I was using `SharedModelManager.SaveStaticData()` at first as well as `StaticData.ToString()` both resulting in a full, but somewhat mangled, dump. Your approach is definitely nicer and works beautifully, thanks again!
