### ISSUE TITLE
converting numeric data

### ISSUE THREAD

**Issue by grBIN** [Da-Teach/RaidStaticData#4]
Hello, today I was converting the data into a format convenient for me and I just can't understand how the basic characteristics of the characters are formed.
How do I convert numeric data to regular format?
128849018880 to 30
or
322122547200 in 13215

**Comment by Da-Teach** [comment]
Hi, Raid uses a special "Fixed" class which stores numeric data as int64 values. A conversion to flat integers is done by right-shifting 32 bits.  If the value needs to be converted to number (e.g. with decimals), dividing by 2^32 will do that.  Depending on which value you are looking at, sometimes special multipliers apply.  This is, for example, the case with health/defense/attack for champions (and might hold true for other values).
